version: "3"
services:
  appserver:
    container_name: pyserver
    hostname: localhost
    image: basic_python
    ports:
      - "5000:5000"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    privileged: true
