"""student grades

Revision ID: 337a12da193e
Revises: 0de71468f032
Create Date: 2025-09-20 21:40:39.665709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337a12da193e'
down_revision = '0de71468f032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('course_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_grade')
    # ### end Alembic commands ###
